name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    name: dep
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ENV: prod
    steps:
      ### PREPARE
      - name: Checkout project
        uses: actions/checkout@v3

      - name: npm
        uses: ./.github/actions/install-node

      ### BUILD
      - name: Build
        run: npx nx build hello-wastex

      ### DEPLOY
